package GameClient;

import Room.RoomManage;
import java.io.IOException;
import java.net.Socket;
import javax.swing.JOptionPane;


public class Login_frame extends javax.swing.JFrame {
    private ListenServer client;
    private javax.swing.JButton button_go;
    private javax.swing.JLabel button_label;
    private javax.swing.JButton button_quit;
    private javax.swing.JTextField button_username;
    private boolean success = false;
    
    private static final String IP="192.168.100.5";
    private static final int PORT=9999;
    
    public Login_frame() {
        setVisible(true);
        setLocation(400, 200);
        initComponents();
        connect();
    }
    
    private void connect(){
        try {
            Socket SOCK = new Socket(IP, PORT);
            System.out.println("Someone Connect Success.");
            client = new ListenServer(SOCK);
            client.remote_Login_frame(this);
            Thread x = new Thread(client);
            x.start();
        } catch (IOException ex) {
            
        }
    }
    
     private void LoginButtonAction()
    {
        
        client.getTransferMethod().SEND("LOGIN");
        client.getTransferMethod().SEND(button_username.getText());
        client.setWaitting();
        if(success == true)
        {
            client.setClientName(button_username.getText());
            new RoomManage(client).setVisible(true);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(null, "CONNECT ERROR !!!");
    }

    public void LoginSuccess(boolean s)
    {
        success = s;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        button_label = new javax.swing.JLabel();
        button_username = new javax.swing.JTextField();
        button_go = new javax.swing.JButton();
        button_quit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        button_label.setBackground(java.awt.SystemColor.textHighlight);
        button_label.setFont(new java.awt.Font("Tahoma", 1, 24));
        button_label.setForeground(new java.awt.Color(0, 140, 255));
        button_label.setText("Star Wars");
        button_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        button_username.setName("button_username");
        button_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_usernameActionPerformed(evt);
            }
        });

        button_go.setFont(new java.awt.Font("Tahoma", 1, 20));
        button_go.setForeground(new java.awt.Color(110, 107, 107));
        button_go.setText("Go");
        button_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonAction(evt);
            }
        });

        button_quit.setFont(new java.awt.Font("Tahoma", 1, 20)); 
        button_quit.setForeground(new java.awt.Color(102, 102, 102));
        button_quit.setText("Quit");
        button_quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(button_username, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_go, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_quit, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_label)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(button_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(button_username, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(button_go, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_quit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }

    private void LoginButtonAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonAction
        // TODO add your handling code here:
        LoginButtonAction();
    }//GEN-LAST:event_LoginButtonAction

    private void button_quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button_quitActionPerformed

    private void button_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Connect_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Connect_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Connect_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Connect_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login_frame().setVisible(true);
        });
    }

}
